npogrpi/calculator/urls.py
from django.urls import path

from . import views

app_name = 'calculator'

urlpatterns = [
    path('calculator/', views.product_search, name='product_search'),
    path('mgrp/', views.mgrp, name='mgrp')
]

npogrpi/npogrpi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import TemplateView

from website.sitemap import ProductSitemap, StaticSitemap, TypeProductSitemap

sitemaps = {
    'static': StaticSitemap,
    'type_product': TypeProductSitemap,
    'products': ProductSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]


urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('website.urls')),
    path('calculator/', include('calculator.urls')),
    path('tinymce/', include('tinymce.urls')),
)

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

npogrpi/website/urls.py
from django.urls import path

from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.catalog, name ='catalog'),
    path('catalog/<slug:type_slug>/', views.type_product, name = 'type_product'),
    path('catalog/<slug:type_slug>/<slug:product_slug>/', views.product_card, name='product_card'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('politico/', views.PoliticoStaticPage.as_view(), name = 'politico'),
]

npogrpi/website/models.py
from django.db import models
from django.urls import reverse
from tinymce.models import HTMLField


class MainPage(models.Model):
    main_image = models.ImageField(upload_to='media/website/',
                                   help_text='Изображение для главной страницы',
                                   blank=True,
                                   )
    about = models.TextField(help_text='Описание компании на главной странице',
                             verbose_name='Описание краткое',
                             )
    about_en = models.TextField(help_text='Short description on main page',
                             verbose_name='Short description',
                             blank=True,
                             null=True,
                             )
    main_title = models.CharField(help_text='Заголовок и meta',
                                  verbose_name='Заголовок главной страницы',
                                  max_length=250,
                                  )
    main_title_en = models.CharField(help_text='Title and meta tag',
                                  verbose_name='Title of main page and meta tag',
                                  max_length=250,
                                  blank=True,
                                  null=True,
                                  )
    
    def __str__(self):
       return self.main_title
    
    class Meta:
        verbose_name = 'Главная страница'
        verbose_name_plural = 'Главная страница'

    
class Partner(models.Model):
    name = models.CharField(help_text='Наименование партнера',
                            verbose_name='Название партера',
                            max_length=150,
                            )
    image = models.ImageField(upload_to='media/website/',
                              help_text='Логотип партнера',
                              height_field=None, 
                              width_field=None, 
                              max_length=None,
                              blank=True,
                              )
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Наш партнёр'
        verbose_name_plural = 'Наши партнёры'

class Advantages(models.Model):
    name = models.CharField(help_text='Заголовок',
                            verbose_name='Наименование преимущества',
                            max_length=100,
                            )
    name_en = models.CharField(help_text='Title',
                            verbose_name='Advantages title',
                            max_length=100,
                            blank=True,
                            null=True,
                            )
    text = models.TextField(help_text='Описание',
                            verbose_name='Описание преимущества',
                            )
    text_en = models.TextField(help_text='Description',
                            verbose_name='Description of advatages',
                            blank=True,
                            null=True,
                            )
    image = models.ImageField(upload_to='media/advantages/',
                              help_text='Загрузите иконку',
                              verbose_name='Изображение преимущества',
                              )
    
    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name= 'Наше преимущество'
        verbose_name_plural = 'Наши преимущества'

class About(models.Model):
    text = HTMLField(verbose_name='Описание компании',
                            help_text='Текст о компании',
                            )
    text_en = HTMLField(verbose_name='Descrteion company',
                            help_text='About company full descrintion',
                            blank=True,
                            null=True,
                            )
    title = models.CharField(verbose_name='Заголовок',
                             max_length=250,
                             )
    title_en = models.CharField(verbose_name='Title',
                             max_length=250,
                             blank=True,
                             null=True,
                             )
    
    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'О нас'
        verbose_name_plural = 'О нас'

class Contacts(models.Model):
    email = models.EmailField(verbose_name='e-mail для связи',
                              help_text='e-mail для связи c контактным лицом',
                              )
    telephone = models.CharField(verbose_name='контактный телефон',
                                 help_text='контактный телефон',
                                 max_length=15,
                                 )
    adress = models.TextField(verbose_name='адрес комапании',
                              help_text='почтовый адрес',
                              blank=True,
                              null=True
                            )
    adress_en = models.TextField(verbose_name='Adress',
                              help_text='Post adress',
                              blank=True,
                              null=True
                            )
    
    def __str__(self) -> str:
        return self.adress
    
    class Meta:
        verbose_name= 'Контакт'
        verbose_name_plural = 'Контакты'


class Type(models.Model):
    name = models.CharField(max_length=300,
                            verbose_name='Тип оборудования',
                            )
    name_en = models.CharField(max_length=300,
                            verbose_name='Type',
                            blank=True,
                            null=True
                            )
    slug = models.SlugField(max_length=300,
                            unique=True,
                            db_index=True,
                            verbose_name='URL',
                            )
    image = models.ImageField(verbose_name='Изображение',
                              upload_to='media/img/type/',
                              help_text='Добавьте файл c изображением',
                              )
    inmgrp = models.BooleanField(default=False,
                                 verbose_name='Оборудование входит в комплект',
                                 )
    incalc = models.BooleanField(default=False,
                                 verbose_name='Включить в калькулятор',
                                 )
    public = models.BooleanField(default=False,
                                 verbose_name='Опубликовано',
                                 )
    seo_description = models.CharField(max_length=160,
                                       verbose_name='Описание для поисковиков, <160 символов',
                                       )
    seo_keywords = models.CharField(max_length=300,
                                    verbose_name='ключевые слова через запятую <10',
                                    )
    created = models.DateField(auto_now_add=True,
                               verbose_name="Создано",)
    updated = models.DateField(auto_now=True,
                               verbose_name="Обновлено",)
    
    class Meta:
        verbose_name = 'Тип оборудования'
        verbose_name_plural = 'Типы оборудования'
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('type_product', kwargs={'type_slug': self.slug})


class DiameterShank(models.Model):
    meaning = models.IntegerField(verbose_name='Значение')

    def __str__(self):
        return str(self.meaning)

    class Meta:
        verbose_name = 'Условный диаметр хвостовика'
        verbose_name_plural = 'Условный диаметр хвостовика'
    

class DiameterColumn(models.Model):
    meaning = models.IntegerField(verbose_name='Значение', 
                                  default=None,)

    def __str__(self):
        return str(self.meaning)

    class Meta:
        verbose_name = 'Условный диаметр колонны'
        verbose_name_plural = 'Условный диаметр колонны'
    

class DiameterOpenBorehole(models.Model):
    meaning = models.DecimalField(max_digits=5,
                                  decimal_places=1,
                                  verbose_name='Значение')
    
    def __str__(self):
        return str(self.meaning)

    class Meta:
        verbose_name = 'Диаметр открытого ствола'
        verbose_name_plural = 'Диаметр открытого ствола'


class Product(models.Model):
    name = models.CharField(max_length=300,
                            verbose_name='Наименование оборудования',
                            )
    name_en = models.CharField(max_length=300,
                            verbose_name='Product name',
                            blank=True,
                            null=True,
                            )
    type = models.ForeignKey(Type, 
                             verbose_name='Тип оборудования', 
                             on_delete=models.CASCADE,
                             related_name='products',
                             )
    description = HTMLField(verbose_name='Описание')
    description_en = HTMLField(verbose_name='Описание',
                               blank=True,
                               null=True,
                               )
    image = models.ImageField(verbose_name='Изображение',
                              upload_to='media/img/product/',
                              help_text='Добавьте файл c изображением'
                              )
    price = models.FloatField(verbose_name='Цена')
    slug = models.SlugField(max_length=300,
                            db_index=True,
                            verbose_name='URL')
    diameter_column = models.ManyToManyField(DiameterColumn,
                                            verbose_name='Условный диаметр колонны',

npogrpi/website/views.py
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.translation import get_language
from django.views.generic.base import TemplateView

from core.forms import ContactForm
from core.views import contact_view

from .models import (About, Advantages, Contacts, MainPage, Partner, Product,
                     Type)


def index(request):
    page_obj = get_object_or_404(MainPage)
    partners = Partner.objects.all()
    advantages = Advantages.objects.all()
    
    if get_language() == 'en':
        page_obj.display_about = page_obj.about_en
        page_obj.display_main_title = page_obj.main_title_en
        for adv in advantages:
            adv.display_name = adv.name_en
            adv.display_text = adv.text_en
    else:
        page_obj.display_about = page_obj.about
        page_obj.display_main_title = page_obj.main_title
        for adv in advantages:
            adv.display_name = adv.name
            adv.display_text = adv.text_en 
    context = {
        'page_obj': page_obj,
        'partners': partners,
        'advantages': advantages,
    }

    return render(request, 'website/index.html', context)


def catalog(request):
    page_obj = Type.objects.filter(public__in=[True])
    if get_language() == 'en':
        for odj in page_obj:
            odj.display_name = odj.name_en
    else:
        for odj in page_obj:
            odj.display_name = odj.name
    context = {
        'page_obj': page_obj,
    }

    return render(request, 'website/catalog.html', context)
#тут закончила

def type_product(request, type_slug):

    type_instance = get_object_or_404(Type, slug=type_slug)
    product_list = type_instance.products.filter(public__in=[True])
    if get_language() == 'en':
        for odj in product_list:
            odj.display_name = odj.name_en
    else:
        for odj in product_list:
            odj.display_name = odj.name
    context = {
        'type_instance': type_instance,
        'product_list': product_list,
    }

    return render(request, 'website/type_product.html', context)


def product_card(request, type_slug, product_slug):

    product = get_object_or_404(Product, slug=product_slug)
    if get_language() == 'en':
        product.display_name = product.name_en
        product.display_description = product.description_en
    else:
        product.display_name = product.name
        product.display_description = product.description
    context = {
        'product':product,
        'type_slug': type_slug,
    }

    return render(request, 'website/product_card.html', context)


def about(request):

    page_obj = About.objects.all()
    if get_language() == 'en':
            page_obj.display_text = page_obj.text_en
            page_obj.display_title = page_obj.title_en
    else:
            page_obj.display_text = page_obj.text
            page_obj.display_title = page_obj.title

    context = {
        'page_obj': page_obj,
    }

    return render(request, 'website/about.html', context)


def contacts(request):

    page_obj = Contacts.objects.all()
    form = ContactForm()
    contact_view(request)
    if get_language() == 'en':
            page_obj.display_adress = page_obj.adress_en
    else:
            page_obj.display_adress = page_obj.adress
    context = {
        'page_obj': page_obj,
        'form':form,
    }

    return render(request, 'website/contacts.html', context)


class PoliticoStaticPage(TemplateView):
    # В переменной template_name обязательно указывается имя шаблона,
    # на основе которого будет создана возвращаемая страница
    template_name = 'website/politico.html' 

npogrpi/templates/website/about.html
{% extends 'base.html' %}
{% load i18n %}
{% load thumbnail %}
{% block title %}
{% trans "О компании" %}
{% endblock %}
{% block meta_tag %}
<meta name="description" content="Краткое описание страницы">
<meta
  name="keywords"
  content="ключевое слово 1, ключевое слово 2, ключевое слово 3">
{% endblock %}
{% block content %}
<nav>
<ul class="breadcrumbs">
  <li><a href="{% url 'website:index' %}">{% trans "Главная" %}</a></li>
  <li>{% trans "О компании" %}</li>
</ul>
</nav>
{% for page in page_obj %}
<section class="about">
  <h2>{{ page.title }}</h2>
  <div class="about-content">
    <p> {{ page.text|safe }} </p>
</div>
</section>
{% endfor %}

  <div class="advantages-container">
    <h2>{% trans "Наши преимущества" %}</h2>
        {% for advantage in advantages %}
          <div class="advantage">
             <img src="{{ advantage.image.url }}" />
             <h3>{{ advantage.name }}</h3>
             <p>{{ advantage.text }} </p>
          </div>
        {% endfor %}  
      </div>
  </div>
  
    <section class="partners">
      <h2>{% trans "Наши партнеры" %}</h2>
      <div class="carousel">
          <button class="carousel-button left-button">&#10094;</button>
          <div class="carousel-track-container">
              <ul class="carousel-track">
                {% for partner in partners %}
                  <li><img src="{{ partner.image.url }}" alt="{{ partner.name }}"></li>
                {% endfor %}
              </ul>
          </div>
          <button class="carousel-button right-button">&#10095;</button>
      </div>
    </section> 
{% endblock %}

npogrpi/templates/website/catalog.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load i18n %}
{% block title %}
{% trans "Каталог продукции" %}
{% endblock %}
{% block meta_tag %}
<meta name="description" content="Краткое описание страницы">
<meta
  name="keywords"
  content="ключевое слово 1, ключевое слово 2, ключевое слово 3">
{% endblock %}
{% block content %}
<nav>
  <ul class="breadcrumbs">
    <li><a href="{% url 'website:index' %}">{% trans "Главная" %}</a></li>
    <li>{% trans "Каталог" %}</li>
  </ul>
</nav>
<div class="button-container">
<a href="javascript:history.back()" class="btn">{% trans "Назад" %}</a>
<a href="{% url 'calculator:product_search' %}" class="btn">{% trans "Подборать оборудование" %}</a>
<a href="{% url 'calculator:mgrp' %}" class="btn">{% trans "Подобрать комплект МГРП" %}</a>
</div>
<section class="catalog-container">
    {% for page in page_obj %}
    <section class="catalog-section">
      <div class="catalog-image">
        <img src="{{page.image.url}}" alt={{ page.name }}>
   		</div>
   		 <div class="catalog-info">
            <h2>{{ page.display_name }}</h2>
            <a href="{% url 'website:type_product' type_slug=page.slug %}" class="details-button">{% trans "Подробнее" %}</a>
        </div>
</section>
{% endfor %} 
{% endblock %}

npogrpi/templates/website/contacts.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
{% trans "Наши контакты" %}
{% endblock %} 
{% block meta_tag %}
<meta name="description" content="Краткое описание страницы">
<meta
  name="keywords"
  content="ключевое слово 1, ключевое слово 2, ключевое слово 3">
{% endblock %}
{% block content %}
<nav>
  <ul class="breadcrumbs">
    <li><a href="{% url 'website:index' %}">{% trans "Главная" %}</a></li>
    <li>{% trans "Наши контакты" %}</li>
  </ul>
</nav>
<div class="contact-container">
  <h2>{% trans "Наши контакты" %}</h2>

  <div class="contact-info">
    <div class="left">
      <h3>{% trans "Информация о компании" %}:</h3>
    {% for page in page_obj %}
      <p><strong>{% trans "Адрес" %}:</strong>{{ page.adress }}</p>
      <p><strong>{% trans "E-mail" %}:</strong> <a href="mailto:info@grpi.ru">{{ page.email }}</a></p>
      <p><strong>{% trans "Телефон" %}:</strong> <a href="tel:+74912470006">{{ page.telephone }}</a></p>
    </div>
    {% endfor %}
    <div class="right">
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">{% trans "Отправить" %}</button>
    </form>
    {% if success_message %}
    <div class="alert alert-success">
        {{ success_message }}
    </div>
    {% endif %}
    </div>
  </div>
  <p>{% trans "Нажимая кнопку «Отправить», вы соглашаетесь на" %} <a href="{% url 'website:politico' %}">{% trans "обработку персональных данных" %}</a></p>
</div>
{% endblock %} 

npogrpi/templates/website/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load thumbnail %}
{% block title %}
   {{ page_obj.display_main_title }}
{% endblock %}
{% block meta_tag %}
<meta name="description" content="Краткое описание страницы">
<meta
  name="keywords"
  content="ключевое слово 1, ключевое слово 2, ключевое слово 3">
{% endblock %}
{% block content %}
<section class="hero">
  <img class="full-width" src="{{ page_obj.main_image.url }}" alt="Баннер">
  <div class="hero-text">
      <h1>{% trans "Добро пожаловать в нашу компанию!" %}</h1>
        <p>{% trans "Мы предлагаем высококачественные услуги." %}</p>
      <a href="{% url 'website:catalog' %}" class="btn">{% trans "Перейти в каталог" %}</a>
  </div>
</section>
<div class="button-container">
<a href="{% url 'calculator:product_search' %}" class="btn">{% trans "Подборать оборудование" %}</a>
<a href="{% url 'calculator:mgrp' %}" class="btn">{% trans "Подобрать комплект МГРП" %}</a>
</div>
<section class="about">
    <h2>{% trans "О компании" %}</h2>
    <div class="about-content">
      <p> {{ page_obj.display_about }} </p>
    <a href="{% url 'website:about' %}" class="details-button">{% trans "Подробнее" %}</a>
  </div>
</section>
<div class="advantages-container">
  <h2>{% trans "Наши преимущества" %}</h2>
      {% for advantage in advantages %}
        <div class="advantage">
           <img src="{{ advantage.image.url }}" />
           <h3>{{ advantage.name }}</h3>
           <p>{{ advantage.text }} </p>
        </div>
      {% endfor %}
    </div>
</div>
  <section class="partners">
    <h2>{% trans "Наши партнеры" %}</h2>
    <div class="carousel">
        <button class="carousel-button left-button">&#10094;</button>
        <div class="carousel-track-container">
            <ul class="carousel-track">
              {% for partner in partners %}
                <li><img src="{{ partner.image.url }}" alt="{{ partner.name }}"></li>
              {% endfor %}
            </ul>
        </div>
        <button class="carousel-button right-button">&#10095;</button>
    </div>
	</section> 
{% endblock %}

npogrpi/templates/website/product_card.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
  {{ product.name }}
{% endblock %}
{% block meta_tag %}
<meta name="description" content="{{ product.seo_description }}">
<meta
  name="keywords"
  content="{{ product.seo_keywords }}">
{% endblock %}
{% block content %}
<nav>
  <ul class="breadcrumbs">
    <li><a href="{% url 'website:index' %}">{% trans "Главная" %}</a></li>
    <li><a href="{% url 'website:catalog' %}">{% trans "Каталог" %}</a></li>
    <li><a href="{% url 'website:type_product' type_slug=type_slug %}">{{ product.type }}</a></li>
    <li>{{ product.name }}</li>
  </ul>
</nav>
<div class="button-container">
  <a href="javascript:history.back()" class="btn">{% trans "Назад" %}</a>
</div>
<div class="product-card">
  <h1 class="product-title">{{ product.name }}</h1>
  <div class="product-info">
      <div class="product-image">
          <img src="{{ product.image.url }}" alt="{{ product.name }}">
      </div>
      <div class="product-details">
          <p class="product-type">{% trans "Тип" %}: {{ product.type }}</p>
          <p class="product-description">{% trans "Описание" %}: {{ product.description|safe }}</p>
          <table class="product-specs">
              <tr>
                  <th>{% trans "Характеристики" %}</th>
                  <th>{% trans "Значение" %}</th>
              </tr>
              <tr>
                  <td>{% trans "Условный диаметр хвостовика" %}</td>
                  <td style="text-align: right;">
                    <ul>
                      {% for shank in product.diameter_shank.all %}
                      <li>{{ shank }}</li>
                      {% endfor %}
                    </ul>
                  </td>
              </tr>
              <tr>
                  <td>{% trans "Условный диаметр колонны" %}</td>
                  <td style="text-align: right;">
                    <ul>
                    {% for column in product.diameter_column.all %}
                      <li>{{ column }}</li>
                    {% endfor %}
                  </ul>
                 </td>
              </tr>
              <tr>
                <td>{% trans "Диаметр открытого ствола" %}</td>
                <td style="text-align: right;">
                  <ul>
                  {% for diameter in product.diameter_open_borehole.all %}
                    <li>{{ diameter }}</li>
                  {% endfor %}
                  </ul>
                </td>
            </tr>
            <tr>
              <td>{% trans "Наружный диаметр оснастки" %}</td>
              <td style="text-align: right;">{{ product.fitting_outer_diameter }}</td>
          </tr>
            <tr>
              <td>{% trans "Внутренний диаметр оснастки" %}</td>
              <td style="text-align: right;">{{ product.fitting_inner_diameter }}</td>
            </tr>
            <tr>
              <td>{% trans "Длина оснастки" %}</td>
              <td style="text-align: right;">{{ product.fitting_length }}</td>
            </tr>
              <!-- Другие характеристики -->
          </table>
      </div>
  </div>
</div>
{% endblock %}

npogrpi/templates/website/type_product.html
{% extends 'base.html' %}
{% load i18n %}
{% load thumbnail %}
{% block title %}
{{ type_instance.name }}
{% endblock %}
{% block meta_tag %}
<meta name="description" content="{{ type_instance.seo_description }}">
<meta
  name="keywords"
  content="{{ type_instance.seo_keywords }}">
{% endblock %}
{% block content %}
<nav>
  <ul class="breadcrumbs">
    <li><a href="{% url 'website:index' %}">{% trans "Главная" %}</a></li>
    <li><a href="{% url 'website:catalog' %}">{% trans "Каталог" %}</a></li>
    <li>{{ type_instance.name }}</li>
  </ul>
</nav>
<div class="button-container">
  <a href="javascript:history.back()" class="btn">{% trans "Назад" %}</a>
  <a href="{% url 'calculator:product_search' %}" class="btn">{% trans "Подборать оборудование" %}</a>
  <a href="{% url 'calculator:mgrp' %}" class="btn">{% trans "Подобрать комплект МГРП" %}</a>
</div>
<h2>{{ type_instance.name }}</h2>
<section class="catalog-container">
    {% for product in product_list %}
    <section class="catalog-section">
      <div class="catalog-image">
        <img src="{{ product.image.url }}" alt={{ product.name }}>
   		</div>
   		 <div class="catalog-info">
            <h2>{{ product.name }}</h2>
            <p>{{ product.description|safe }}
              <a href="{% url 'website:product_card' type_slug=type_instance.slug product_slug=product.slug %}" class="details-button">{% trans "Подробнее" %}</a>
        </div>
</section>
{% endfor %} 
{% endblock %}