npogrpi/calculator/urls.py
from django.urls import path

from . import views

app_name = 'calculator'

urlpatterns = [
    path('calculator/', views.product_search, name='product_search'),
    path('mgrp/', views.mgrp, name='mgrp')
]

npogrpi/npogrpi/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns
from django.views.generic.base import TemplateView

from website.sitemap import ProductSitemap, StaticSitemap, TypeProductSitemap

sitemaps = {
    'static': StaticSitemap,
    'type_product': TypeProductSitemap,
    'products': ProductSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('robots.txt/', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]


urlpatterns += i18n_patterns(
    path("i18n/", include("django.conf.urls.i18n")),
    path('', include('website.urls')),
    path('calculator/', include('calculator.urls')),
    path('tinymce/', include('tinymce.urls')),
)

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

npogrpi/website/urls.py
from django.urls import path

from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
    path('catalog/', views.catalog, name ='catalog'),
    path('catalog/<slug:type_slug>/', views.type_product, name = 'type_product'),
    path('catalog/<slug:type_slug>/<slug:product_slug>/', views.product_card, name='product_card'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('politico/', views.PoliticoStaticPage.as_view(), name = 'politico'),
]

npogrpi/calculator/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _



class ContactSearch(models.Model):
    name = models.CharField(max_length=100,
                            verbose_name=_('Имя'),
                            )
    phone_number = models.CharField(max_length=20,
                                    verbose_name=_('Телефон'),
                                    )
    email = models.EmailField()
    company = models.CharField(max_length=100,
                               verbose_name=_('Компания'),
                               )

    def __str__(self):
        return self.name

npogrpi/calculator/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from website.models import (DiameterColumn, DiameterOpenBorehole,
                            DiameterShank, Type)

from .models import ContactSearch


class ProductSearchForm(forms.ModelForm):
    class Meta:
        model = ContactSearch
        fields = ['name', 'phone_number', 'email', 'company', 'type', 'diameter_column', 'diameter_shank', 'diameter_open_borehole']

    type = forms.ModelChoiceField(queryset=Type.objects.filter(incalc__in=[True]), label=_('Тип оборудования'))
    diameter_column = forms.ModelChoiceField(queryset=DiameterColumn.objects.all(), label=_('Условный диаметр колонны'))
    diameter_shank = forms.ModelChoiceField(queryset=DiameterShank.objects.all(), label=_('Условный диаметр хвостовика'))
    diameter_open_borehole = forms.ModelChoiceField(queryset=DiameterOpenBorehole.objects.all(), label=_('Диаметр открытого ствола'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['diameter_column'].queryset = DiameterColumn.objects.all()
        self.fields['diameter_shank'].queryset = DiameterShank.objects.all()
        self.fields['diameter_open_borehole'].queryset = DiameterOpenBorehole.objects.all()

        #if 'type' in self.data:
            #try:
                #type_id = int(self.data.get('type'))
                #self.fields['diameter_column'].queryset = DiameterColumn.objects.filter(type_id=type_id)
                #self.fields['diameter_shank'].queryset = DiameterShank.objects.filter(type_id=type_id)
                #self.fields['diameter_open_borehole'].queryset = DiameterOpenBorehole.objects.filter(type_id=type_id)
           # except (ValueError, TypeError):
                #pass

class ProductSelectionForm(forms.ModelForm):
    class Meta:
        model = ContactSearch
        fields = ['name', 'phone_number', 'email', 'company', 'diameter_column', 'diameter_shank', 'diameter_open_borehole', 'stages_quantity']
    #type_choices = [(type.slug, type.name) for type in Type.objects.filter(inmgrp__in=[True])]
    diameter_column = forms.ModelChoiceField(queryset=DiameterColumn.objects.all(), label=_('Условный диаметр колонны'))
    diameter_shank = forms.ModelChoiceField(queryset=DiameterShank.objects.all(), label=_('Условный диаметр хвостовика'))
    diameter_open_borehole = forms.ModelChoiceField(queryset=DiameterOpenBorehole.objects.all(), label=_('Диаметр открытого ствола'))
    stages_quantity = forms.IntegerField(label=_('Количество стадий'))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['type'].choices = [(type.slug, type.name) for type in Type.objects.filter(inmgrp=True)]


    def clean(self):
        cleaned_data = super().clean()
        stages_quantity = cleaned_data.get('stages_quantity')
        if stages_quantity is not None and stages_quantity <= 0:
            raise forms.ValidationError('Количество стадий должно быть положительным числом')
        return cleaned_data

npogrpi/calculator/views.py
from django.shortcuts import render

from core.send import send_email_to_admin
from website.models import Product

from .forms import ProductSearchForm, ProductSelectionForm


def product_search(request):
    if request.method == 'POST':
        form = ProductSearchForm(request.POST)
        if form.is_valid():
            type = form.cleaned_data['type']
            diameter_column = form.cleaned_data['diameter_column']
            diameter_shank = form.cleaned_data['diameter_shank']
            diameter_open_borehole = form.cleaned_data['diameter_open_borehole']

            # Фильтрация продукции
            products = Product.objects.filter(
                incalc__in=[True],
                type=type,
                diameter_column=diameter_column,
                diameter_shank=diameter_shank,
                diameter_open_borehole=diameter_open_borehole
            )

            if products.exists():
                # Если найдены продукты, отображаем результат
                send_email_to_admin(form.cleaned_data)
                return render(request, 'calculator/result.html', {'products': products})
            else:
                # Если ничего не найдено, отображаем сообщение
                return render(request, 'calculator/no_result.html')
    else:
        form = ProductSearchForm()

    return render(request, 'calculator/calculator.html', {'form': form})

def mgrp(request):
    if request.method == 'POST':
        form = ProductSelectionForm(request.POST)
        if form.is_valid():
            diameter_column = form.cleaned_data['diameter_column']
            diameter_shank = form.cleaned_data['diameter_shank']
            diameter_open_borehole = form.cleaned_data['diameter_open_borehole']
            stages_quantity = form.cleaned_data['stages_quantity']

            # Расчет количества оборудования
            packers_quantity = stages_quantity
            ball_sleeves_quantity = max(0, stages_quantity - 1)
            hydraulic_sleeves_quantity = 1
            activation_sleeves_quantity = 1
            quanitys = {
                'packers_quantity': packers_quantity,
                'ball_sleeves_quantity': ball_sleeves_quantity,
                'hydraulic_sleeves_quantity': hydraulic_sleeves_quantity,
                'activation_sleeves_quantity': activation_sleeves_quantity
            }

            # Получение продукции
            products = Product.objects.filter(
                type__inmgrp__in=[True],
                diameter_column=diameter_column,
                diameter_shank=diameter_shank,
                diameter_open_borehole=diameter_open_borehole
            )

            if products.exists():
                send_email_to_admin(form.cleaned_data)
                total_price = 0.0
                for prod in products:
                    if prod.type.slug == 'paker':
                        total_price += prod.price * stages_quantity
                    elif prod.type.slug == 'mufta_grp_sharovaiya':
                        total_price += prod.price * (stages_quantity - 1)
                    else:
                        total_price += prod.price
                
                context = {
                    'products': products,
                    'stages_quantity':stages_quantity,
                    'quanitys':quanitys,
                    'total_price':total_price,
                }
                return render(request, 'calculator/mgrp_result.html', context)
            else:
                return render(request, 'calculator/no_result.html')
    else:
        form_mgrp = ProductSelectionForm()
    return render(request, 'calculator/mgrp.html', {'form_mgrp': form_mgrp})

npogrpi/templates/calculator/calculator.html
{% extends 'base.html' %}
{% load i18n %}
{% load thumbnail %}
{% block title %}
{% trans "Подбор оборудования" %}
{% endblock %}
{% block content %}
<nav>
  <ul class="breadcrumbs">
    <li><a href="{% url 'website:index' %}">{% trans "Главная" %}</a></li>
    <li>{% trans "Подбор оборудования" %}</li>
</ul>
  </nav>
<div class="button-container">
    <a href="javascript:history.back()" class="btn">{% trans "Назад" %}</a>
</div>
<h1>{% trans "Подбор оборудования" %}</h1>
<div class="form-center">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">{% trans "Найти" %}</button>
  </form>
</div>
<p>{% trans "Нажимая кнопку «Найти», вы соглашаетесь на" %}<a href="{% url 'website:politico' %}">{% trans "обработку персональных данных" %}</a></p>
{% endblock %}

npogrpi/templates/calculator/mgrp.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Подбор оборудования
{% endblock %}
{% block content %}
<nav>
  <ul class="breadcrumbs">
    <li><a href="{% url 'website:index' %}">Главная</a></li>
    <li>Подбор коплекта МГРП</li>
</ul>
</nav>
<div class="button-container">
  <a href="javascript:history.back()" class="btn">Назад</a>
</div>
<h1>Форма для подбора оборудования</h1>
<div class="form-center">
<form method="post">
    {% csrf_token %}
    {{ form_mgrp.as_p }}
    <button type="submit">Найти</button>
</form>
</div>
<p>Нажимая кнопку «Найти», вы соглашаетесь на <a href="{% url 'website:politico' %}">обработку персональных данных</a></p>
{% endblock %}

npogrpi/templates/calculator/mgrp_result.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Результат
{% endblock %}
{% block content %}
<h1 align="center">Результат подбора оборудования для {{ stages_quantity }} стадий </h1>
{% if products %}
<div class="container">
<div class="table-container">
    <table class="center">
        <thead>
            <tr>
                <th>Тип продукции</th>
                <th>Наименование продукции</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>{{ product.type }}</td>
                    <td><a href="{% url 'website:product_card' type_slug=product.type.slug product_slug=product.slug %}" 
                        target="_blank">{{ product.name }}</a></td>
                </tr>
            {% endfor %} 
            <table class="center">
                <thead>
                    <tr>
                        <th>Количество</th>
                    </tr>
                    {% for quanity in quanitys.values %} 
                    <tr>
                        <td>{{ quanity }}</td>
                    </tr>  
                    {% endfor %}         
                </thead>
                <tbody>
        </tbody>
    </table>
</div>
</div>
<h2>Общая стоимость оборудования: {{ total_price }} руб.</h2>
<p>Помимо представленного комплекта для МГРП, спускаемый хвостовик должен быть оснащен полным набором 
    технологической оснастки - в зависимости от вида заканчивания (цементируемое или нецементируемое) 
    и индивидуальных потребностей конкретного заказчика. 
    Со всей предлагаемой оснасткой хвостовиков вы можете ознакомиться в электронном <a href="{% url 'website:catalog' %}">каталоге.</a></p>
<a href="{% url 'website:contacts' %}"> Наши контакты</a>
{% else %}
    <p>Оборудование не найдено. Свяжитесь с нашими менеджерами.</p>
{% endif %}
{% endblock %}

npogrpi/templates/calculator/no_result.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Результат
{% endblock %}
{% block content %}
<div class="button-container">
    <a href="javascript:history.back()" class="btn">Назад</a>
</div>
<p>Оборудование не найдено. Свяжитесь с нашими менеджерами.</p>
<a href="{% url 'website:contacts' %}"> Наши контакты</a>
<ul>
    <li>Телефон: <a href="tel:+74912470006">+7 4912 47-00-06</a></li>
    <li>Email: <a href="mailto:info@grpi.ru">info@grpi.ru</a></li>
</ul>
{% endblock %}

npogrpi/templates/calculator/result.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
Результат
{% endblock %}
{% block content %}
<div class="button-container">
    <a href="javascript:history.back()" class="btn">Назад</a>
</div>
<h1>Подбор оборудования</h1>
    {% for product in products %}
    <div class="product-card">
        <h1 class="product-title">{{ product.name }}</h1>
        <div class="product-info">
            <div class="product-image">
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
            </div>
            <div class="product-details">
                <p class="product-description">Описание: {{ product.description|safe }}</p>
                <p class="product-type">Цена: {{ product.price }} руб. </p>
                <a href="{% url 'website:product_card' type_slug=product.type.slug product_slug=product.slug %}" class="details-button">Подробнее</a>
            </div>
        </div>
    </div>
        <!-- Остальные поля продукта -->
    {% endfor %}
{% endblock %}